mod 'puppet/nginx', '1.0.0'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs-apache', '7.0.0'
mod 'samuelson/dockeragent'
mod 'puppetlabs/docker'
mod 'puppetlabs-firewall'
